contact_links:
  - name: GitHub Community Support
    url: https://github.com/wiscaksono/x-shopee-remover/discussions
    about: Please leave your questions here or on Discord - Link below "Security Bug Bounty"
